spring:
  kafka:
   bootstrap-servers: localhost:9092
   consumer:
     group-id: message-group
  datasource:
    url: jdbc:mysql://localhost:3306/user-module
    username: root
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  boot:
#    admin:
#      client:
#        url: http://localhost:1111
  data:
    redis:
      host: localhost
      port: 6379
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true
server:
  port: 8002

aws:
   access-key: ${aws_access_key}
   secret-key: ${aws_secret_key}
   region: ${aws_region}
   bucket-name: ${aws_bucket_name}
