spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-module
    username: root
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: pdf-group

razorpay:
  key_id: ${rzp_key_id}
  key_secret: ${rzp_key_secret}

