spring:
  application:
    name: USER-API
  datasource:
    url: jdbc:mysql://database-1.ctyceg88ibsj.ap-south-1.rds.amazonaws.com:3306/user-module?createDatabaseIfNotExist=true
    username: root
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  boot:
#    admin:
#      client:
#        url: http://localhost:1111/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: localhost
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

jwt:
  key: siuhdiashcaschasc
  issuer: ankit
  expiry: 86400000

springdoc:
  api-docs:
    enabled: true

server:
  port: 8000

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 100s
        failureRateThreshold: 50
